task:
    regression
model_class:
    ModelLGBMRegressor
model_params:
    nthread: -1
    n_estimators: 10000
    learning_rate: 0.01
    # num_leaves: 34
    # colsample_bytree: 0.9497036
    # subsample: 0.8715623
    # max_depth: 8
    # reg_alpha: 0.041545473
    # reg_lambda: 0.0735294
    # min_split_gain: 0.0222415
    # min_child_weight: 39.3259775
    silent: -1
    verbose: -1
    random_state: 2019
    boosting_type: gbdt
    lambda_l1: 0.04076595481757882
    lambda_l2: 0.030536332917474082
    max_depth: 12
    num_leaves: 39
    min_data_in_leaf: 100
    feature_fraction: 0.9536794495481166
    bagging_fraction: 0.7867436751328633
    bagging_freq: 1
