features:
    - Activity
    - Assessment
    - Clip
    - Game
    - accumulated_correct_attempts
    - accumulated_uncorrect_attempts
    - ave_accuracy_group
    - ave_accuracy
    - accumulated_actions
    - duration_mean
    - session_title
    - acc_group_0_count
    - acc_group_1_count
    - acc_group_2_count
    - acc_group_3_count
    - game_count
    - title0_count
    - title10_count
    - title11_count
    - title12_count
    - title13_count
    - title14_count
    - title15_count
    - title16_count
    - title17_count
    - title18_count
    - title19_count
    - title1_count
    - title20_count
    - title21_count
    - title22_count
    - title23_count
    - title24_count
    - title25_count
    - title26_count
    - title27_count
    - title28_count
    - title29_count
    - title2_count
    - title30_count
    - title31_count
    - title32_count
    - title33_count
    - title34_count
    - title35_count
    - title36_count
    - title37_count
    - title38_count
    - title39_count
    - title3_count
    - title40_count
    - title41_count
    - title42_count
    - title43_count
    - title4_count
    - title5_count
    - title6_count
    - title7_count
    - title8_count
    - title9_count
    - event_code2000_count
    - event_code2010_count
    - event_code2020_count
    - event_code2025_count
    - event_code2030_count
    - event_code2035_count
    - event_code2040_count
    - event_code2050_count
    - event_code2060_count
    - event_code2070_count
    - event_code2075_count
    - event_code2080_count
    - event_code2081_count
    - event_code2083_count
    - event_code3010_count
    - event_code3020_count
    - event_code3021_count
    - event_code3110_count
    - event_code3120_count
    - event_code3121_count
    - event_code4010_count
    - event_code4020_count
    - event_code4021_count
    - event_code4022_count
    - event_code4025_count
    - event_code4030_count
    - event_code4031_count
    - event_code4035_count
    - event_code4040_count
    - event_code4045_count
    - event_code4050_count
    - event_code4070_count
    - event_code4080_count
    - event_code4090_count
    - event_code4095_count
    - event_code4100_count
    - event_code4110_count
    - event_code4220_count
    - event_code4230_count
    - event_code4235_count
    - event_code5000_count
    - event_code5010_count

categorical_features:
    - session_title
