features:
    - Activity
    - Assessment
    - Clip
    - Game
    - accumulated_correct_attempts
    - accumulated_uncorrect_attempts
    - ave_accuracy_group
    - ave_accuracy
    - accumulated_actions
    - duration_mean
    - session_title
    - acc_group_0_count
    - acc_group_1_count
    - acc_group_2_count
    - acc_group_3_count
    - game_count
    # ----------------------------------
    - title12_false_attempts_count
    - title12_true_attempts_count
    - title18_false_attempts_count
    - title18_true_attempts_count
    - title21_false_attempts_count
    - title21_true_attempts_count
    - title2_false_attempts_count
    - title2_true_attempts_count
    - title30_false_attempts_count
    - title30_true_attempts_count
    # ----------------------------------
    - title12_ave_accracy
    - title12_ave_accracy_group
    - title18_ave_accracy
    - title18_ave_accracy_group
    - title21_ave_accracy
    - title21_ave_accracy_group
    - title2_ave_accracy
    - title2_ave_accracy_group
    - title30_ave_accracy
    - title30_ave_accracy_group
    # ----------------------------------
    - title12_last_acc_group
    - title18_last_acc_group
    - title21_last_acc_group
    - title2_last_acc_group
    - title30_last_acc_group
    # ----------------------------------
    - title0_count
    - title10_count
    - title11_count
    - title12_count
    - title13_count
    - title14_count
    - title15_count
    - title16_count
    - title17_count
    - title18_count
    - title19_count
    - title1_count
    - title20_count
    - title21_count
    - title22_count
    - title23_count
    - title24_count
    - title25_count
    - title26_count
    - title27_count
    - title28_count
    - title29_count
    - title2_count
    - title30_count
    - title31_count
    - title32_count
    - title33_count
    - title34_count
    - title35_count
    - title36_count
    - title37_count
    - title38_count
    - title39_count
    - title3_count
    - title40_count
    - title41_count
    - title42_count
    - title43_count
    - title4_count
    - title5_count
    - title6_count
    - title7_count
    - title8_count
    - title9_count
    # ----------------------------------
    - event_code2000_count
    - event_code2010_count
    - event_code2020_count
    - event_code2025_count
    - event_code2030_count
    - event_code2035_count
    - event_code2040_count
    - event_code2050_count
    - event_code2060_count
    - event_code2070_count
    - event_code2075_count
    - event_code2080_count
    - event_code2081_count
    - event_code2083_count
    - event_code3010_count
    - event_code3020_count
    - event_code3021_count
    - event_code3110_count
    - event_code3120_count
    - event_code3121_count
    - event_code4010_count
    - event_code4020_count
    - event_code4021_count
    - event_code4022_count
    - event_code4025_count
    - event_code4030_count
    - event_code4031_count
    - event_code4035_count
    - event_code4040_count
    - event_code4045_count
    - event_code4050_count
    - event_code4070_count
    - event_code4080_count
    - event_code4090_count
    - event_code4095_count
    - event_code4100_count
    - event_code4110_count
    - event_code4220_count
    - event_code4230_count
    - event_code4235_count
    - event_code5000_count
    - event_code5010_count
    - title0_event2000_count
    - title10_event2000_count
    - title11_event2000_count
    - title12_event2000_count
    - title12_event2010_count
    - title12_event2020_count
    - title12_event2025_count
    - title12_event2030_count
    - title12_event2035_count
    - title12_event3010_count
    - title12_event3020_count
    - title12_event3021_count
    - title12_event3110_count
    - title12_event3120_count
    - title12_event3121_count
    - title12_event4020_count
    - title12_event4025_count
    - title12_event4030_count
    - title12_event4035_count
    - title12_event4040_count
    - title12_event4070_count
    - title12_event4080_count
    - title12_event4090_count
    - title12_event4100_count
    - title13_event2000_count
    - title13_event2020_count
    - title13_event2030_count
    - title13_event3010_count
    - title13_event3020_count
    - title13_event3021_count
    - title13_event3110_count
    - title13_event3120_count
    - title13_event3121_count
    - title13_event4010_count
    - title13_event4020_count
    - title13_event4025_count
    - title13_event4030_count
    - title13_event4035_count
    - title13_event4070_count
    - title13_event4080_count
    - title13_event4090_count
    - title13_event4100_count
    - title14_event2000_count
    - title15_event2000_count
    - title15_event3010_count
    - title15_event3110_count
    - title15_event4020_count
    - title15_event4030_count
    - title15_event4070_count
    - title15_event4080_count
    - title15_event4090_count
    - title16_event2000_count
    - title16_event2020_count
    - title16_event2030_count
    - title16_event2080_count
    - title16_event2081_count
    - title16_event2083_count
    - title16_event3010_count
    - title16_event3020_count
    - title16_event3021_count
    - title16_event3110_count
    - title16_event3120_count
    - title16_event3121_count
    - title16_event4010_count
    - title16_event4020_count
    - title16_event4030_count
    - title16_event4035_count
    - title16_event4040_count
    - title16_event4045_count
    - title16_event4070_count
    - title16_event4080_count
    - title16_event4090_count
    - title16_event4095_count
    - title17_event2000_count
    - title17_event2010_count
    - title17_event3010_count
    - title17_event3110_count
    - title17_event4020_count
    - title17_event4021_count
    - title17_event4025_count
    - title17_event4070_count
    - title17_event4090_count
    - title17_event5000_count
    - title17_event5010_count
    - title18_event2000_count
    - title18_event2010_count
    - title18_event2020_count
    - title18_event2030_count
    - title18_event3010_count
    - title18_event3020_count
    - title18_event3021_count
    - title18_event3110_count
    - title18_event3120_count
    - title18_event3121_count
    - title18_event4020_count
    - title18_event4030_count
    - title18_event4035_count
    - title18_event4040_count
    - title18_event4070_count
    - title18_event4080_count
    - title18_event4090_count
    - title18_event4100_count
    - title19_event2000_count
    - title1_event2000_count
    - title1_event2020_count
    - title1_event2030_count
    - title1_event2040_count
    - title1_event2050_count
    - title1_event2080_count
    - title1_event2081_count
    - title1_event2083_count
    - title1_event3010_count
    - title1_event3020_count
    - title1_event3021_count
    - title1_event3110_count
    - title1_event3120_count
    - title1_event3121_count
    - title1_event4010_count
    - title1_event4020_count
    - title1_event4070_count
    - title1_event4090_count
    - title20_event2000_count
    - title21_event2000_count
    - title21_event2010_count
    - title21_event2020_count
    - title21_event2030_count
    - title21_event3010_count
    - title21_event3020_count
    - title21_event3021_count
    - title21_event3110_count
    - title21_event3120_count
    - title21_event3121_count
    - title21_event4020_count
    - title21_event4025_count
    - title21_event4030_count
    - title21_event4035_count
    - title21_event4040_count
    - title21_event4070_count
    - title21_event4080_count
    - title21_event4090_count
    - title21_event4100_count
    - title21_event4110_count
    - title22_event2000_count
    - title23_event2000_count
    - title24_event2000_count
    - title25_event2000_count
    - title26_event2000_count
    - title26_event2020_count
    - title26_event2025_count
    - title26_event2030_count
    - title26_event3010_count
    - title26_event3020_count
    - title26_event3021_count
    - title26_event3110_count
    - title26_event3120_count
    - title26_event3121_count
    - title26_event4010_count
    - title26_event4020_count
    - title26_event4030_count
    - title26_event4035_count
    - title26_event4070_count
    - title26_event4080_count
    - title26_event4090_count
    - title26_event4095_count
    - title27_event2000_count
    - title27_event2020_count
    - title27_event2030_count
    - title27_event2060_count
    - title27_event2070_count
    - title27_event3010_count
    - title27_event3020_count
    - title27_event3021_count
    - title27_event3110_count
    - title27_event3120_count
    - title27_event3121_count
    - title27_event4010_count
    - title27_event4020_count
    - title27_event4070_count
    - title27_event4080_count
    - title27_event4090_count
    - title28_event2000_count
    - title28_event2020_count
    - title28_event2025_count
    - title28_event2030_count
    - title28_event2035_count
    - title28_event2080_count
    - title28_event2083_count
    - title28_event3010_count
    - title28_event3020_count
    - title28_event3021_count
    - title28_event3110_count
    - title28_event3120_count
    - title28_event3121_count
    - title28_event4010_count
    - title28_event4020_count
    - title28_event4040_count
    - title28_event4045_count
    - title28_event4070_count
    - title28_event4080_count
    - title28_event4090_count
    - title28_event4095_count
    - title28_event4220_count
    - title28_event4230_count
    - title28_event4235_count
    - title29_event2000_count
    - title29_event2020_count
    - title29_event3010_count
    - title29_event3110_count
    - title29_event4020_count
    - title29_event4025_count
    - title29_event4070_count
    - title29_event4080_count
    - title29_event4090_count
    - title2_event2000_count
    - title2_event2010_count
    - title2_event2020_count
    - title2_event2030_count
    - title2_event3010_count
    - title2_event3020_count
    - title2_event3021_count
    - title2_event3110_count
    - title2_event3120_count
    - title2_event3121_count
    - title2_event4020_count
    - title2_event4025_count
    - title2_event4030_count
    - title2_event4035_count
    - title2_event4040_count
    - title2_event4070_count
    - title2_event4080_count
    - title2_event4090_count
    - title2_event4100_count
    - title30_event2000_count
    - title30_event2010_count
    - title30_event2020_count
    - title30_event2030_count
    - title30_event3010_count
    - title30_event3020_count
    - title30_event3021_count
    - title30_event3110_count
    - title30_event3120_count
    - title30_event3121_count
    - title30_event4020_count
    - title30_event4025_count
    - title30_event4030_count
    - title30_event4035_count
    - title30_event4040_count
    - title30_event4070_count
    - title30_event4080_count
    - title30_event4090_count
    - title30_event4100_count
    - title31_event2000_count
    - title32_event2000_count
    - title32_event3010_count
    - title32_event3110_count
    - title32_event4020_count
    - title32_event4022_count
    - title32_event4030_count
    - title32_event4035_count
    - title32_event4070_count
    - title32_event4080_count
    - title32_event4090_count
    - title33_event2000_count
    - title34_event2000_count
    - title34_event2020_count
    - title34_event2030_count
    - title34_event3010_count
    - title34_event3110_count
    - title34_event4020_count
    - title34_event4030_count
    - title34_event4035_count
    - title34_event4070_count
    - title34_event4080_count
    - title34_event4090_count
    - title35_event2000_count
    - title35_event2020_count
    - title35_event2030_count
    - title35_event3010_count
    - title35_event3020_count
    - title35_event3021_count
    - title35_event3110_count
    - title35_event3120_count
    - title35_event3121_count
    - title35_event4010_count
    - title35_event4020_count
    - title35_event4030_count
    - title35_event4035_count
    - title35_event4070_count
    - title35_event4080_count
    - title35_event4090_count
    - title35_event4095_count
    - title36_event2000_count
    - title37_event2000_count
    - title37_event3010_count
    - title37_event3110_count
    - title37_event4020_count
    - title37_event4022_count
    - title37_event4025_count
    - title37_event4030_count
    - title37_event4070_count
    - title37_event4080_count
    - title37_event4090_count
    - title38_event2000_count
    - title39_event2000_count
    - title3_event2000_count
    - title3_event3010_count
    - title3_event3110_count
    - title3_event4020_count
    - title3_event4021_count
    - title3_event4030_count
    - title3_event4035_count
    - title3_event4070_count
    - title3_event4080_count
    - title3_event4090_count
    - title40_event2000_count
    - title40_event2020_count
    - title40_event2030_count
    - title40_event2060_count
    - title40_event2070_count
    - title40_event2075_count
    - title40_event3010_count
    - title40_event3020_count
    - title40_event3021_count
    - title40_event3110_count
    - title40_event3120_count
    - title40_event3121_count
    - title40_event4010_count
    - title40_event4020_count
    - title40_event4070_count
    - title40_event4080_count
    - title40_event4090_count
    - title40_event4095_count
    - title41_event2000_count
    - title42_event2000_count
    - title43_event2000_count
    - title4_event2000_count
    - title4_event2020_count
    - title4_event2030_count
    - title4_event2060_count
    - title4_event2070_count
    - title4_event2075_count
    - title4_event3010_count
    - title4_event3020_count
    - title4_event3021_count
    - title4_event3110_count
    - title4_event3120_count
    - title4_event3121_count
    - title4_event4010_count
    - title4_event4020_count
    - title4_event4030_count
    - title4_event4031_count
    - title4_event4070_count
    - title4_event4080_count
    - title4_event4090_count
    - title5_event2000_count
    - title5_event2020_count
    - title5_event2030_count
    - title5_event3010_count
    - title5_event3020_count
    - title5_event3021_count
    - title5_event3110_count
    - title5_event3120_count
    - title5_event3121_count
    - title5_event4010_count
    - title5_event4020_count
    - title5_event4050_count
    - title5_event4070_count
    - title5_event4090_count
    - title6_event2000_count
    - title6_event3010_count
    - title6_event3110_count
    - title6_event4025_count
    - title6_event4030_count
    - title6_event4035_count
    - title6_event4070_count
    - title6_event4080_count
    - title6_event4090_count
    - title7_event2000_count
    - title8_event2000_count
    - title8_event2020_count
    - title8_event2030_count
    - title8_event2060_count
    - title8_event2070_count
    - title8_event2075_count
    - title8_event3010_count
    - title8_event3020_count
    - title8_event3021_count
    - title8_event3110_count
    - title8_event3120_count
    - title8_event3121_count
    - title8_event4010_count
    - title8_event4020_count
    - title8_event4070_count
    - title8_event4090_count
    - title8_event4100_count
    - title8_event4110_count
    - title9_event2000_count

categorical_features:
    - session_title
