- exp_name: '20200120020348'
  model_name: 002_lgbm_baseline
  weight: 2

- exp_name: '20200120011438'
  model_name: 102_catboost_regression
  weight: 3

- exp_name: '20200120031400'
  model_name: 300_nn_regression
  weight: 1
