- exp_name: '20200121215504'
  model_name: 002_lgbm_baseline
  weight: 2

- exp_name: '20200121222559'
  model_name: 102_catboost_regression
  weight: 3

- exp_name: '20200121232047'
  model_name: 300_nn_regression
  weight: 1
